name: Update Portfolio JSON hourly

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch: # Allow manual trigger too

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.18"

      - name: Install dependencies
        run: pip install requests

      - name: Run JSON update script
        run: python update_portfolio.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add projects_data.json
          git commit -m "🔄 Hourly portfolio update [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master
          
      - name: Purge jsDelivr cache
        run: curl -X GET "https://purge.jsdelivr.net/gh/kishandev2509/githubInfoJson@master/projects_data.json"
